djangobin/MainApp/urls.py
from django.conf.urls import url,include
from MainApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #APis
    url(r'^api/', include('MainApp.api.urls', namespace='restapi')),
    #forms
    url(r'^loginform/$',views.login_form,name='login-form-handler'),
    url(r'^signupform/$',views.signup_form,name='signup-form-handler'),
    url(r'^postformhandle/$',views.post_form_upload,name='post-form'),
    url(r'^$',views.base_view.as_view(template_name='home.html'),name='home'),
    url(r'^search/$',views.base_view.as_view(template_name='all-posts.html'),name='view-all'),
    url(r'^all/$',views.base_view.as_view(template_name='infiscroll.html'),name='infiscroll'),
    # url(r'^private/$',views.privatePosts.as_view(template_name='private-posts.html'),name='view-private'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^signup/$',views.sign_up_view,name='sign-up'),
    url(r'^(?P<slug>[-\w]+)/$', views.post_detail_view.as_view(template_name='detail-view.html'), name='detail'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangobin/djangobin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from MainApp import urls

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'',include('MainApp.urls',namespace='MainApp')),
]

djangobin/templates/all-posts.html
{% extends 'base.html' %}
{% load  staticfiles %}
{% load crispy_forms_tags %}

{% block extrahead %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'datatable/dataTables.bootstrap.min.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}

    <div class="container">




        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
{#                    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>#}

                    {% for object in latest_posts %}
                         <li><a href=" {% url 'MainApp:detail' object.slug %} ">{{ object.title|title }} ({{ object.timestamp|timesince }} before)</a></li>
                    {% endfor %}

                <li><a href="/all/">View All</a></li>
                </ul>


            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

                <h1 class="page-header">
                    Paste Way
                    <small>an ultra minimal <kbd>ctl+v</kbd></small>
                </h1>

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info alert-dismissible" id="faded" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}







            <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Title</th>
                <th>Attachements</th>
                <th>writer</th>
                <th>Likes</th>
                <th>Hits</th>
                <th>Timestamp</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Title</th>
                <th>Attachements</th>
                <th>writer</th>
                <th>Likes</th>
                <th>Hits</th>
                <th>Timestamp</th>
            </tr>
        </tfoot>
        <tbody>


        {% for post in all_posts %}

            <tr>
                <td><a href=" {% url 'MainApp:detail' post.slug %} ">
                    {{ post.title|capfirst }}
                </a></td>
                <td>
                    {% if post.files %}
                        <a href="{{ post.files.url }}" target="_blank">
                            <button type="button" class="btn btn-block btn-primary">View</button>
                        </a>
                    {% endif %}

                </td>
                <td>{{ post.writer.first_name }} </td>
                <td>{{ post.likes }}</td>
                <td>{{ post.hits }}</td>
                <td>{{ post.timestamp }}</td>
            </tr>

         {% endfor %}

{#                    {% for post in custom_objects %}#}
{#              <!-- First Blog Post -->#}
{#                <h2>#}
{#                    <a href="#">{{ post.title|capfirst }}</a>#}
{#                </h2>#}
{#                <p class="lead">#}
{#                    by <a href="#">{{ post.writer.first_name }}</a>#}
{#                </p>#}
{#                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.timestamp }}</p>#}
{#                <hr>#}
{#                {% if  post.image %}#}
{#                    <img class="img-responsive" src="{{ post.image.url }}" alt="">#}
{#                  <hr>#}
{#                {% endif %}#}
{##}
{#                <p>{{ post.content|safe|escape }}</p>#}
{#                <a class="btn btn-primary" href="#">Read More <span#}
{#                        class="glyphicon glyphicon-chevron-right"></span></a>#}
{##}
{#                <hr>#}
{##}
{#            {% endfor %}#}


        </tbody>
    </table>


{#            {% for post in custom_objects %}#}
{#              <!-- First Blog Post -->#}
{#                <h2>#}
{#                    <a href="#">{{ post.title|capfirst }}</a>#}
{#                </h2>#}
{#                <p class="lead">#}
{#                    by <a href="#">{{ post.writer.first_name }}</a>#}
{#                </p>#}
{#                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.timestamp }}</p>#}
{#                <hr>#}
{#                {% if  post.image %}#}
{#                    <img class="img-responsive" src="{{ post.image.url }}" alt="">#}
{#                  <hr>#}
{#                {% endif %}#}
{##}
{#                <p>{{ post.content|safe|escape }}</p>#}
{#                <a class="btn btn-primary" href="#">Read More <span#}
{#                        class="glyphicon glyphicon-chevron-right"></span></a>#}
{##}
{#                <hr>#}
{##}
{#            {% endfor %}#}



{##}
{#                <!-- Pager -->#}
{#                <ul class="pager">#}
{#                    <li class="previous">#}
{#                        <a href="#">&larr; Older</a>#}
{#                    </li>#}
{#                    <li class="next">#}
{#                        <a href="#">Newer &rarr;</a>#}
{#                    </li>#}
{#                </ul>#}


                <br>
                <br>
                <br>
                <hr>


                <footer>
                    <p> Created by <a href="http://github.com/tomvictor" target="_blank">Tom Victor</a>.</p>
                </footer>

            </div>
        </div>


    </div>


{% endblock %}

{% block extrascripts %}



    <!-- javascript -->
		<script type="text/javascript" src="{% static 'datatable/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatable/dataTables.bootstrap.min.js' %}"></script>
   <script>
     $(document).ready(function() {
    $('#example').DataTable();
} );

    </script>

{% endblock %}

djangobin/templates/base.html
{% load  staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}

    {% block extrahead %}

    {% endblock %}

</head>

<body>

{% include 'navbar.html' %}


{% block content %}

{% endblock %}


{% include 'scripts.html' %}
{% block extrascripts %}
{% endblock %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71760892-2', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

djangobin/templates/detail-view.html
{% extends 'base.html' %}
{% load  staticfiles %}
{% load crispy_forms_tags %}

{% block extrahead %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}

    <div class="container">




        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
{#                    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>#}

                    {% for object in latest_posts %}
                         <li><a href=" {% url 'MainApp:detail' object.slug %}">{{ object.title|title }} ({{ object.timestamp|timesince }} before)</a></li>
                    {% endfor %}
                <li><a href="/all/">View All</a></li>

                </ul>

            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">


                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info alert-dismissible" id="faded" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}



             <!-- Blog Post -->

                <!-- Title -->
                <h1>{{ thisPost.title }}</h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">{{ thisPost.writer.first_name }}</a>
                </p>


                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ thisPost.timestamp }}</p>

                <hr>

                <!-- Preview Image -->
                            {% if  thisPost.image %}
                    <img class="img-responsive" src="{{ thisPost.image.url }}" alt="">
                  <hr>
                {% endif %}



                <!-- Post Content -->
             {{ thisPost.content|safe|escape }}
{#                <hr>#}

             {% if  thisPost.files %}
                    <h4><a href="{{ thisPost.files.url }}" target="_blank">
                        View Attachements
                    </a></h4>
                  <hr>
                {% endif %}

                <!-- Blog Comments -->

{#                <a href="{{ thisPost.get_absolute_url }}">#}
{#                     <h1>{{ thisPost.get_absolute_url }}</h1>#}
{#                </a>#}


            <div id="disqus_thread"></div>
                <script>
                    /**
                     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                     var disqus_config = function () {
                         var  canurl = "http://pasteway.com{{ thisPost.get_absolute_url }}" ;
                     this.page.url = canurl;  // Replace PAGE_URL with your page's canonical URL variable
                     this.page.identifier = "{{ thisPost.slug }}" ; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                     };
                    (function () { // DON'T EDIT BELOW THIS LINE
                        var d = document, s = d.createElement('script');
                        s.src = 'https://pasteway.disqus.com/embed.js';
                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments
                    powered by Pasteway.</a></noscript>



{#                <!-- Comments Form -->#}
{#                <div class="well">#}
{#                    <h4>Leave a Comment:</h4>#}
{#                    <form role="form">#}
{#                        <div class="form-group">#}
{#                            <textarea class="form-control" rows="3"></textarea>#}
{#                        </div>#}
{#                        <button type="submit" class="btn btn-primary">Submit</button>#}
{#                    </form>#}
{#                </div>#}
{##}
{#                <hr>#}

{#                <!-- Posted Comments -->#}
{##}
{#                <!-- Comment -->#}
{#                <div class="media">#}
{#                    <a class="pull-left" href="#">#}
{#                        <img class="media-object" src="http://placehold.it/64x64" alt="">#}
{#                    </a>#}
{#                    <div class="media-body">#}
{#                        <h4 class="media-heading">Start Bootstrap#}
{#                            <small>August 25, 2014 at 9:30 PM</small>#}
{#                        </h4>#}
{#                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <!-- Comment -->#}
{#                <div class="media">#}
{#                    <a class="pull-left" href="#">#}
{#                        <img class="media-object" src="http://placehold.it/64x64" alt="">#}
{#                    </a>#}
{#                    <div class="media-body">#}
{#                        <h4 class="media-heading">Start Bootstrap#}
{#                            <small>August 25, 2014 at 9:30 PM</small>#}
{#                        </h4>#}
{#                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.#}
{#                        <!-- Nested Comment -->#}
{#                        <div class="media">#}
{#                            <a class="pull-left" href="#">#}
{#                                <img class="media-object" src="http://placehold.it/64x64" alt="">#}
{#                            </a>#}
{#                            <div class="media-body">#}
{#                                <h4 class="media-heading">Nested Start Bootstrap#}
{#                                    <small>August 25, 2014 at 9:30 PM</small>#}
{#                                </h4>#}
{#                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.#}
{#                            </div>#}
{#                        </div>#}
{#                        <!-- End Nested Comment -->#}
{#                    </div>#}
{#                </div>#}
{##}


                </br>
                <hr>

                </br>


                <footer>
                    <p> Created by <a href="http://github.com/tomvictor" target="_blank">Tom Victor</a>.</p>
                </footer>

            </div>
        </div>


    </div>


{% endblock %}

{% block extrascripts %}

    <!-- javascript -->
		<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugin/tinymce/tinymce.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugin/tinymce/init-tinymce.js' %}"></script>

{% endblock %}

djangobin/templates/head.html
{% load  staticfiles %}
{% load crispy_forms_tags %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Tom Victor">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>Pasteway.com</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'ie10-viewport-bug-workaround.css' %}" rel="stylesheet">



    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

djangobin/templates/home.html
{% extends 'base.html' %}
{% load  staticfiles %}
{% load crispy_forms_tags %}

{% block extrahead %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}

    <div class="container">




        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
{#                    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>#}

                    {% for object in latest_posts %}
                         <li><a href=" {% url 'MainApp:detail' object.slug %}">{{ object.title|title }} ({{ object.timestamp|timesince }} before)</a></li>
                    {% endfor %}
                <li><a href="/all/">View All</a></li>

                </ul>

            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

{#                <h1 class="page-header">#}
{#                    Paste Way#}
{#                    <small>an ultra minimal <kbd>ctl+v</kbd></small>#}
{#                </h1>#}

            <center>
                <img class="img-responsive" src="{% static "logo/pasteway.png" %}" alt="" width="450">
            </center>

            <center>
                <h1 class="page-header">
{#                    Paste Way#}
                    <small>An ultra minimal <kbd>ctl+v</kbd></small>
                </h1>
            </center>


                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info alert-dismissible" id="faded" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}


                <div class="row ">
                    <form role="form" action="/postformhandle/" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <button class="btn btn-lg btn-success " type="submit">Submit</button>
                    </form>

                </div>

                </br>
                <hr>

                </br>





{#            {% for post in custom_objects %}#}
{#              <!-- First Blog Post -->#}
{#                <h2>#}
{#                    <a href="#">{{ post.title|capfirst }}</a>#}
{#                </h2>#}
{#                <p class="lead">#}
{#                    by <a href="#">{{ post.writer.first_name }}</a>#}
{#                </p>#}
{#                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.timestamp }}</p>#}
{#                <hr>#}
{#                {% if  post.image %}#}
{#                    <img class="img-responsive" src="{{ post.image.url }}" alt="">#}
{#                  <hr>#}
{#                {% endif %}#}
{##}
{#                <p>{{ post.content|safe|escape }}</p>#}
{#                <a class="btn btn-primary" href="#">Read More <span#}
{#                        class="glyphicon glyphicon-chevron-right"></span></a>#}
{##}
{#                <hr>#}
{##}
{#            {% endfor %}#}



{##}
{#                <!-- Pager -->#}
{#                <ul class="pager">#}
{#                    <li class="previous">#}
{#                        <a href="#">&larr; Older</a>#}
{#                    </li>#}
{#                    <li class="next">#}
{#                        <a href="#">Newer &rarr;</a>#}
{#                    </li>#}
{#                </ul>#}



                <footer>
                    <p> Created by <a href="http://github.com/tomvictor" target="_blank">Tom Victor</a>.</p>
                </footer>

            </div>
        </div>


    </div>


{% endblock %}

{% block extrascripts %}

    <!-- javascript -->
		<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
        <script type="text/javascript" src="/static/plugin/tinymce/tinymce.min.js"></script>
        <script type="text/javascript" src="/static/plugin/tinymce/init-tinymce.js"></script>

{% endblock %}

djangobin/templates/infiscroll.html
{% extends 'base.html' %}
{% load  staticfiles %}
{% load crispy_forms_tags %}

{% block extrahead %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'datatable/dataTables.bootstrap.min.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}

    <div class="container">


        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    {#                    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>#}

                    {% for object in latest_posts %}
                        <li><a href=" {% url 'MainApp:detail' object.slug %} ">{{ object.title|title }}
                            ({{ object.timestamp|timesince }} before)</a></li>
                    {% endfor %}

                    <li><a href="/all/">View All</a></li>
                </ul>


            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

                <h1 class="page-header">
                    Paste Way
                    <small>an ultra minimal <kbd>ctl+v</kbd></small>
                </h1>

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info alert-dismissible" id="faded" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

                <!-- First Blog Post -->
             <div id="posts">
            {% for object in latest_posts %}
                    <h2>
                        <a href="{% url 'MainApp:detail' object.slug %}"> {{ object.title|title }} </a>
                    </h2>

                    <p><span class="glyphicon glyphicon-time"></span> {{ object.timestamp|timesince }}</p>

                {{ object.content|safe|escape }}

                    <hr>

                    {% endfor %}

                </div>

                <center>
                    <p id="loading">
                    <img src="{% static "Loading_icon.gif" %}" alt="Loading…"/>
                </p>
                </center>



                {#            {% for post in custom_objects %}#}
                {#              <!-- First Blog Post -->#}
                {#                <h2>#}
                {#                    <a href="#">{{ post.title|capfirst }}</a>#}
                {#                </h2>#}
                {#                <p class="lead">#}
                {#                    by <a href="#">{{ post.writer.first_name }}</a>#}
                {#                </p>#}
                {#                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.timestamp }}</p>#}
                {#                <hr>#}
                {#                {% if  post.image %}#}
                {#                    <img class="img-responsive" src="{{ post.image.url }}" alt="">#}
                {#                  <hr>#}
                {#                {% endif %}#}
                {##}
                {#                <p>{{ post.content|safe|escape }}</p>#}
                {#                <a class="btn btn-primary" href="#">Read More <span#}
                {#                        class="glyphicon glyphicon-chevron-right"></span></a>#}
                {##}
                {#                <hr>#}
                {##}
                {#            {% endfor %}#}


                {##}
                {#                <!-- Pager -->#}
                {#                <ul class="pager">#}
                {#                    <li class="previous">#}
                {#                        <a href="#">&larr; Older</a>#}
                {#                    </li>#}
                {#                    <li class="next">#}
                {#                        <a href="#">Newer &rarr;</a>#}
                {#                    </li>#}
                {#                </ul>#}


                <footer>
                    <p> Created by <a href="http://github.com/tomvictor" target="_blank">Tom Victor</a>.</p>
                </footer>

            </div>
        </div>


    </div>


{% endblock %}

{% block extrascripts %}



    <!-- javascript -->
    <script>
        $(document).ready(function () {
            var win = $(window);
            var nextpage = "https://pasteway.com/api/?page=4";

            // Each time the user scrolls
            win.scroll(function () {
                // End of the document reached?
                if ($(document).height() - win.height() == win.scrollTop()) {
                    $('#loading').show();

                    // Uncomment this AJAX call to test it

                    $.ajax({
                        url: nextpage,
                        dataType: 'json',
                        success: function (html) {
                            console.log("insucces function");
                            console.log(html);
                            nextpage = html.next;
                            console.log(html.results);
                            {#                            $('#posts').append(html);#}
                            {#                     $('#loading').hide();#}


                            var post = '<br>';

                            for (count = 0; count < 3; count++) {
                                post += '<h2><a href="/';
                                post += html.results[count].slug;
                                post += '">';
                                post += html.results[count].title;
                                post += '</a></h2><p><span class="glyphicon glyphicon-time"></span> Posted on';
                                post += html.results[count].timestamp;
                                post += '</p>';
                                post += html.results[count].content;
                                post += '<hr>';
                            }


                            $('#posts').append(post);

                            $('#loading').hide();


                        }
                    });

                }
            });
        });


    </script>


{% endblock %}

djangobin/templates/login.html
{% extends 'base.html' %}
{% load  staticfiles %}
{% load crispy_forms_tags %}
{% block extrahead %}
    <!-- Custom CSS -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <br>
            <br>
            <br>


            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ page_title }}</h3>
                </div>


                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info alert-dismissible" id="faded" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="panel-body">
                    {% if pageurl == "login" %}
                        <form role="form" action="/loginform/" method="post">
                    {% elif pageurl == "signup" %}
                        <form role="form" action="/signupform/" method="post">
                    {% endif %}

                    {% csrf_token %}
                    <fieldset>

                        {{ form|crispy }}

                        <!-- Change this to a button or input when using this as a form -->

                        {% if pageurl == "login" %}

                             <button class="btn btn-lg btn-success btn-block" type="submit">Login</button>
                    {% elif pageurl == "signup" %}
                         <button class="btn btn-lg btn-success btn-block" type="submit">Sign Up</button>
                    {% endif %}

                    </fieldset>
                    </form>
                </div>
            </div>

        </div>
    </div>


{% endblock %}

{% block extrafooter %}
{% endblock %}